"""Repository for generated image operations."""

from typing import List, Optional
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from sqlalchemy import desc

from chorus_engine.models.conversation import GeneratedImage


class ImageRepository:
    """Handle database operations for generated images."""
    
    def __init__(self, db: Session):
        self.db = db
    
    def create(
        self,
        conversation_id: str,
        thread_id: str,
        character_id: str,
        prompt: str,
        workflow_file: str,
        file_path: str,
        negative_prompt: Optional[str] = None,
        message_id: Optional[int] = None,
        thumbnail_path: Optional[str] = None,
        width: Optional[int] = None,
        height: Optional[int] = None,
        seed: Optional[int] = None,
        notes: Optional[str] = None,
        generation_time: Optional[float] = None
    ) -> GeneratedImage:
        """
        Create a new generated image record.
        
        Args:
            conversation_id: Conversation ID
            thread_id: Thread ID
            character_id: Character who generated the image
            prompt: Positive prompt used
            workflow_file: Path to workflow file
            file_path: Path to saved image file
            negative_prompt: Optional negative prompt
            message_id: Optional associated message ID
            thumbnail_path: Optional path to thumbnail
            width: Image width in pixels
            height: Image height in pixels
            seed: Random seed used
            notes: Optional user notes
            generation_time: Time taken to generate (seconds)
        
        Returns:
            Created GeneratedImage record
        """
        image = GeneratedImage(
            conversation_id=conversation_id,
            thread_id=thread_id,
            character_id=character_id,
            prompt=prompt,
            negative_prompt=negative_prompt,
            workflow_file=workflow_file,
            file_path=file_path,
            thumbnail_path=thumbnail_path,
            message_id=message_id,
            width=width,
            height=height,
            seed=seed,
            notes=notes,
            generation_time=generation_time
        )
        
        self.db.add(image)
        self.db.commit()
        self.db.refresh(image)
        
        return image
    
    def get_by_id(self, image_id: int) -> Optional[GeneratedImage]:
        """
        Get generated image by ID.
        
        Args:
            image_id: Image ID
        
        Returns:
            GeneratedImage or None if not found
        """
        return self.db.query(GeneratedImage).filter(GeneratedImage.id == image_id).first()
    
    def get_by_conversation(
        self,
        conversation_id: str,
        limit: Optional[int] = None
    ) -> List[GeneratedImage]:
        """
        Get all images for a conversation.
        
        Args:
            conversation_id: Conversation ID
            limit: Optional limit on number of results
        
        Returns:
            List of GeneratedImage records (newest first)
        """
        query = self.db.query(GeneratedImage).filter(
            GeneratedImage.conversation_id == conversation_id
        ).order_by(desc(GeneratedImage.created_at))
        
        if limit:
            query = query.limit(limit)
        
        return query.all()
    
    def get_by_character(
        self,
        character_id: str,
        limit: Optional[int] = None
    ) -> List[GeneratedImage]:
        """
        Get all images generated by a character.
        
        Args:
            character_id: Character ID
            limit: Optional limit on number of results
        
        Returns:
            List of GeneratedImage records (newest first)
        """
        query = self.db.query(GeneratedImage).filter(
            GeneratedImage.character_id == character_id
        ).order_by(desc(GeneratedImage.created_at))
        
        if limit:
            query = query.limit(limit)
        
        return query.all()
    
    def get_recent(
        self,
        days: int = 7,
        limit: Optional[int] = None
    ) -> List[GeneratedImage]:
        """
        Get recently generated images.
        
        Args:
            days: Number of days to look back
            limit: Optional limit on number of results
        
        Returns:
            List of GeneratedImage records (newest first)
        """
        cutoff = datetime.utcnow() - timedelta(days=days)
        
        query = self.db.query(GeneratedImage).filter(
            GeneratedImage.created_at >= cutoff
        ).order_by(desc(GeneratedImage.created_at))
        
        if limit:
            query = query.limit(limit)
        
        return query.all()
    
    def update_notes(self, image_id: int, notes: str) -> Optional[GeneratedImage]:
        """
        Update notes for an image.
        
        Args:
            image_id: Image ID
            notes: New notes text
        
        Returns:
            Updated GeneratedImage or None if not found
        """
        image = self.get_by_id(image_id)
        
        if image:
            image.notes = notes
            self.db.commit()
            self.db.refresh(image)
        
        return image
    
    def delete(self, image_id: int) -> bool:
        """
        Delete a generated image record.
        
        Args:
            image_id: Image ID
        
        Returns:
            True if deleted, False if not found
        """
        image = self.get_by_id(image_id)
        
        if image:
            self.db.delete(image)
            self.db.commit()
            return True
        
        return False
    
    def delete_by_conversation(self, conversation_id: str) -> int:
        """
        Delete all images for a conversation.
        
        Args:
            conversation_id: Conversation ID
        
        Returns:
            Number of records deleted
        """
        count = self.db.query(GeneratedImage).filter(
            GeneratedImage.conversation_id == conversation_id
        ).delete()
        
        self.db.commit()
        return count
    
    def count_by_character(self, character_id: str) -> int:
        """
        Count total images generated by a character.
        
        Args:
            character_id: Character ID
        
        Returns:
            Total count
        """
        return self.db.query(GeneratedImage).filter(
            GeneratedImage.character_id == character_id
        ).count()
    
    def get_statistics(self) -> dict:
        """
        Get generation statistics.
        
        Returns:
            Dictionary with statistics
        """
        total = self.db.query(GeneratedImage).count()
        
        # Get average generation time
        avg_time_result = self.db.query(
            GeneratedImage.generation_time
        ).filter(
            GeneratedImage.generation_time.isnot(None)
        ).all()
        
        avg_time = None
        if avg_time_result:
            times = [r[0] for r in avg_time_result]
            avg_time = sum(times) / len(times)
        
        # Get most active character
        from sqlalchemy import func
        most_active = self.db.query(
            GeneratedImage.character_id,
            func.count(GeneratedImage.id).label('count')
        ).group_by(
            GeneratedImage.character_id
        ).order_by(
            desc('count')
        ).first()
        
        return {
            "total_images": total,
            "average_generation_time": avg_time,
            "most_active_character": most_active[0] if most_active else None,
            "most_active_count": most_active[1] if most_active else 0
        }
